#!/usr/bin/env python3
""" Generate AllDiff CNF"""


import argparse
from dataclasses import dataclass, field
from io import StringIO

def get_args() -> argparse.Namespace:
    """Parse the cmdline arguments"""
    parser = argparse.ArgumentParser(description="Construct a CNF for all-diff")
    parser.add_argument("--int-bits", type=int, required=True,
                        help="How many bits per integer")
    parser.add_argument("--n-ints", type=int, required=True,
                        help="How many integers to have in all-diff")

    parser.add_argument("--domain-size", type=int,
                        help="The number of possible integer values to choose from")

    args = parser.parse_args()
    args.prog = parser.prog
    return args

class CnfDb:
    """Class containing current CNF status"""
    _num_vars: int = 0
    _num_clauses: int = 0
    _header_comments: list[str]
    _out_stream: StringIO

    def __init__(self):
        self._out_stream = StringIO()
        self._header_comments = []

    def add_var(self) -> int:
        """Add a variable to the CNF"""
        self._num_vars += 1
        return self._num_vars

    def add_clause(self, clause: list[int]) -> int:
        """Add the clause to the CNF

           Each list entry `lit` is:
            - lit>0 for var(lit) == true
            - lit<0 for var(abs(lit)) == false
            - 0: Illegal value, should not be in here
        """
        assert all(lit != 0 for lit in clause)
        self._num_clauses += 1
        print(' '.join(f'{lit}' for lit in clause), 0,
              file=self._out_stream)

    def add_comment(self, comment: str) -> None:
        """Add comment line(s)"""
        for line in comment.splitlines():
            print("c", line,
                  file=self._out_stream)

    def add_header_comment(self, comment: str) -> None:
        """Register the comments that are in the header of the DIMACS CNF file"""
        self._header_comments.extend(comment.splitlines())

    def add_separators(self, count=1) -> None:
        """Add line separators in the final CNF, when supported"""
        print('\n' * count, file=self._out_stream)

    def print(self) -> None:
        """Print the CNF to stdout in DIMACS format"""
        for line in self._header_comments:
            print(f"c {line}")
        print(f"p {self._num_vars} {self._num_clauses}")
        print(self._out_stream.getvalue())


@dataclass
class IntDb:
    """Class responsible for mapping from integer variables to binary variables"""
    int_bits: int
    n_ints: int
    domain_size: int | None
    cnf_db: CnfDb
    _int_var_as_bools: dict[int, list[int]] = field(default_factory=dict)

    def get(self, number: int) -> list[int]:
        """Get the list of boolean variables that represent this number, possibly creating them"""
        result = self._int_var_as_bools.get(number)
        if result is None:
            result =[self.cnf_db.add_var() for _ in range(self.int_bits)]
            self.cnf_db.add_comment(f"int({number}) V{result[0]}..={result[-1]}")
            self._int_var_as_bools[number] = result
        return result


    def add_cnf_header(self, cnf_db: CnfDb, prog: str) -> None:
        """Add the integer info the the CNF header"""
        cnf_db.add_header_comment(f"CNF for all-diff with {self.n_ints} integers with {self.int_bits} bits each")
        if_domain = '' if self.domain_size is None else f' --domain-size={self.domain_size}'
        cnf_db.add_header_comment(f"generated by {prog} --int-bits={self.int_bits} --n-ints={self.n_ints}{if_domain}")


class AllDiffBuilder:
    """Main class to build a CNF for all-diff"""

    def __init__(self, prog: str, int_bits: int, n_ints: int, domain_size: int|None) -> None:
        self.cnf_db = CnfDb()
        self.int_db = IntDb(int_bits=int_bits,
                            n_ints=n_ints,
                            domain_size=domain_size,
                            cnf_db=self.cnf_db)
        self.eq_bool_vars: dict[(int, int), int] = {}
        self._init_eq_bool_vars()
        self.prog = prog

    def _init_eq_bool_vars(self) -> None:
        for first_int_var in range(self.int_db.n_ints):
            first_bool_vars = self.int_db.get(first_int_var)
            for second_int_var in range(self.int_db.n_ints):
                second_bool_vars = self.int_db.get(second_int_var)
                assert len(first_bool_vars) == len(second_bool_vars)
                for first, second in zip(first_bool_vars, second_bool_vars):
                    self._add_unique_eq_bool_var(first, second)

    def _add_unique_eq_bool_var(self, first: int, second: int) -> None:
        """Add a bool var that will hold: var <==> (first == second)
        Add both symmetric entries and avoid adding things which are already known
        """
        if (first, second) in self.eq_bool_vars or first == second:
            return
        var = self.cnf_db.add_var()
        self.eq_bool_vars[(first, second)] = var
        self.eq_bool_vars[(second, first)] = var
        self.cnf_db.add_comment(f'(V{first} == V{second}) iff V{var}')

    def build_cnf(self) -> None:
        """Construct a CNF in DIMACS format and output to stdout"""

        self.build_all_domain_constraints()
        self.build_all_eq_constraints()
        self.build_all_diff_constraints()

        self.int_db.add_cnf_header(self.cnf_db, self.prog)
        self.cnf_db.print()

    def build_all_domain_constraints(self) -> None:
        """If domain is given, then make sure all integers fit the domain restriction"""
        if self.int_db.domain_size is None:
            return
        for int_var in range(self.int_db.n_ints):
            self.build_domain_constraint(int_var)

    def build_domain_constraint(self, int_var: int) -> None:
        """Make sure this integer variable fit the domain size, i.e., value(var) < self.int_db.domain_size"""
        bool_vars = self.int_db.get(int_var)
        if self.int_db.domain_size >= 2**len(bool_vars):
            return
        max_bits = [((self.int_db.domain_size-1) >> bit_index) & 1 for bit_index, _ in enumerate(bool_vars)]

        self.cnf_db.add_comment(f"({self._bool_vars_to_str(bool_vars)}) <= {self.int_db.domain_size-1}")

        # 0 prefix (MSB) will constrain all these MSB to be 0
        while max_bits and max_bits[-1] == 0:
            self.cnf_db.add_clause([max_bits.pop()])
            bool_vars.pop()


        # 1 suffix (LSB) means all these LSB are unconstrained
        while max_bits and max_bits[0] == 1:
            bool_vars.pop(0)
            max_bits.pop(0)
        if not max_bits:
            return

        if max_bits != [0]+ [1] * (len(max_bits)-1):
            raise ValueError("supporting domain sizes up to 2**bits - 2")

        self.cnf_db.add_clause([-var for var in bool_vars])


    def build_all_eq_constraints(self) -> None:
        """Build != constraints between all bits in self.eq_bool_vars"""
        for (first, second), eq_var in self.eq_bool_vars.items():
            if first < second:
                self.build_eq_constraint(first, second, eq_var)

    def build_eq_constraint(self, first: int, second: int, eq_var: int) -> None:
        """
            Equality constraint
              eq_var <==> (first == second)
            is split in 2:
              1. (first == second) -> eq_var
                 And is handled in steps:
                 - (first != second) || eq_var
                 - ((first -> !second) || eq_var) && ((!first -> second) || eq_var)
                 Which gives clauses: (-first, -second, eq_var);  (first, second, eq_var)
              - (first != second) -> !eq_var
                 And is handled in steps:
                 - (first == second) || !eq_var
                 - ((first -> second) || !eq_var) &&
                   ((first -> second) || !eq_var)
                 Which gives clauses: (-first, second, -eq_var);  (first, -second, -eq_var)
        """
        self.cnf_db.add_comment(f"(V{first} == V{second}) <==> V{eq_var}")
        self.cnf_db.add_clause([-first, -second, eq_var])
        self.cnf_db.add_clause([first, second, eq_var])
        self.cnf_db.add_clause([-first, second, -eq_var])
        self.cnf_db.add_clause([first, -second, -eq_var])
        self.cnf_db.add_separators()

    def build_all_diff_constraints(self) -> None:
        """Build all the inequality constraints of all_diff"""
        for first_int in range(self.int_db.n_ints):
            for second_int in range(first_int +1, self.int_db.n_ints):
                self.build_ne_constraint(first_int, second_int)

    def _bool_vars_to_str(self, bool_vars: list[int]) -> str:
        return ', '.join(f'V{bool_var}' for bool_var in bool_vars)

    def build_ne_constraint(self, first_int: int, second_int) -> None:
        """Create a single != constraint, relying on self.eq_bool_vars correctness"""
        first_bools = self.int_db.get(first_int)
        second_bools = self.int_db.get(second_int)
        self.cnf_db.add_comment(f"(int({first_int}) != int({second_int})) :: ({self._bool_vars_to_str(first_bools)}) != ({self._bool_vars_to_str(second_bools)})")

        at_least_one_should_be_false: list[int] = [
            self.eq_bool_vars[(first_bool, second_bool)]
            for first_bool, second_bool in zip(first_bools, second_bools)]

        self.cnf_db.add_clause([-var for var in at_least_one_should_be_false])

def main():
    """The main of this script"""
    args = get_args()
    builder = AllDiffBuilder(prog=args.prog, int_bits=args.int_bits, n_ints=args.n_ints, domain_size=args.domain_size)
    builder.build_cnf()

if __name__ == "__main__":
    main()
